owner: immport-devteam
name: profile_cl
description: uses flowCL to find a match for each of the populations defined by FLOCK
long_description: |
    **Input**
    This tool reads in the population score profiles from FLOCK.
    The marker names need to be in the cell ontology for this to work

    **Output**
    The output is an interactive page that allows visualization of the data.

    https://www.immportgalaxy.org
categories:
    - Flow Cytometry Analysis
remote_repository_url: https://github.com/ImmPortDB/immport-galaxy-tools/tree/master/flowtools/profile_cl
type: unrestricted
