owner: immport-devteam
name: flowclr_summary
description: generates summary statistics on FLOCK output
long_description: |
    **Input**
    Any flowclr file, output from FLOCK or Cross Sample, containing fluorescence intensity value par marker and assigned population.

    **Output**
    This tool produces two reports. One indicates the population distribution in the input file, the other gives descriptive summary statistics per population and marker.

    https://www.immportgalaxy.org
categories:
    - Flow Cytometry Analysis
remote_repository_url: https://github.com/ImmPortDB/immport-galaxy-tools/tree/master/flowtools/flowclr_summary
type: unrestricted
