owner: azomics
name: clustergrammer_flow
description: generates a heat map from the provided input matrix using Clustergrammer
long_description: |
    **Input**
    Please provide a tab-separated matrix of values as input, for instance a centroid file from a FLOCK analysis.
    Rows and columns can be annotated by setting up categories and labels for each group within categories.
    Any type of matrix can be used but the datatype expected by this tool is flowmfi. You can modify the file format of any file in your history by clicking on the pencil next to the name of your file, and going to the 'Datatype' tab.

    **Output**
    The output is an interactive heat-map of the matrix provided.

    https://www.immportgalaxy.org
categories:
    - Flow Cytometry Analysis
remote_repository_url: https://github.com/ImmPortDB/immport-galaxy-tools/tree/master/flowtools/clustergrammer_flow
type: unrestricted
