owner: immport-devteam
name: flowcl
description: uses flowCL to find the most likely match to a given set a markers
long_description: |
    **Input**
    Type in the marker names and select the expression level in the drop-down menu. Marker names need to be in the Cell Ontology for this to work.

    **Output**
    A summary of the ouptut of flowCL is captured in a txt file. For more details, please refer to the flowCL documentation.
    FlowCL generates a plot for the most likely matches to ontology.

    https://www.immportgalaxy.org
categories:
    - Flow Cytometry Analysis
remote_repository_url: https://github.com/ImmPortDB/immport-galaxy-tools/tree/master/flowtools/flowcl
type: unrestricted
