owner: azomics
name: ggcyto_1d_density_plots
description: generates 1D density plots for each markers in FCS file
long_description: |
    **Note**
    This was written by immport-dev-team, only uploaded to the toolshed by azomics user.
    
    **Input**
    This tool FCS files as input.

    **Output file**
    PNG file with series of 1D density plot using ggcyto and produced a png file. A pdf file can optionally be generated.

    https://www.immportgalaxy.org
categories:
    - Flow Cytometry Analysis
remote_repository_url: https://github.com/ImmPortDB/immport-galaxy-tools/tree/master/flowtools/ggcyto_1d_density_plots
type: unrestricted
