owner: azomics
name: flowsom_tree
description: generates a reference Self-Organizing Map using FlowSOM.
long_description: |
    **Note**
    This was written by immport-dev-team, only uploaded to the toolshed by azomics user.
    
    **Input**
    This tool require a valid FCS file or flowFrame as input. Compensation and Transformation will NOT be applied with this tool. Parameters include grid size, number of expected meta-clusters, seed and columns to use for analysis.

    **Output file**
    This tool produces a FlowSOM object and optionally two sets of plots, one representing the SOM Tree generated, and the other displaying each marker's contribution to the tree. A flat text file can also optionally be generated and used as input for vizualisation tools.

    https://www.immportgalaxy.org
categories:
    - Flow Cytometry Analysis
remote_repository_url: https://github.com/ImmPortDB/immport-galaxy-tools/tree/master/flowtools/flowsom_tree
type: unrestricted
