owner: azomics
name: metacyto_search_cl
description: This tool uses MetaCyto to search for clusters of cells corresponding to provided gate definitions.
long_description: |
    **Note**
    This was written by immport-dev-team, only uploaded to the toolshed by azomics user.
    
    **Input**
    This tool requires the pre-processing summary generated for MetaCyto as well as the pre-processed FCS files.
    Cluster definitions
    Please provide gate definitions as comma-separated lists of marker names, for instance "CD3+, CD4+, CD25+, Foxp3+".
    **Output**
    This tool generates a list of provided clusters definitions, as well as a table of the MFI for each marker in each cluster in each file, and proportion of each cluster in each file. A list of unused cluster definitions, if any, is also generated.
    https://www.immportgalaxy.org
categories:
    - Flow Cytometry Analysis
remote_repository_url: https://github.com/AstraZeneca-Omics/immport-galaxy-tools/tree/master/flowtools/metacyto_search_clr
type: unrestricted
