owner: azomics
name: flowsom_compare
description: uses FlowSOM to compare two or more groups of files to a reference FlowSOM tree.
long_description: |
    **Input**
    This tool requires a reference FlowSOM tree, as well as two dataset collections of FCS files. Each group is compared to the reference tree. The statistical differential threshold is based on a Wilcox-test, with a p-value of 0.05 by default. If there is only one group to compare to the tree, the first set of FCS files should be the one used to generate the reference tree.

    **Output file**
    This tool generates a table with groups attribution to each FlowSOM node, as well as a plot per comparison. Tables of counts, mean, median, proportion and normalized mean per node and files or groups are optionally produced.

    https://www.immportgalaxy.org
categories:
    - Flow Cytometry Analysis
remote_repository_url: https://github.com/ImmPortDB/immport-galaxy-tools/tree/master/flowtools/flowsom_compare
type: unrestricted
