owner: immport-devteam
name: flowai
description: automatically performs quality control of flow cytometry data
long_description: |
    **Input**
    One or more FCS files.

    **Output**
    full HTML report
    new FCS file containing only high quality events (default)
    new FCS file containing only low quality events (optional)
    original FCS file containing an additional parameter where the low quality events have a value higher than 10,000 (optional)

    https://www.immportgalaxy.org
categories:
    - Flow Cytometry Analysis
remote_repository_url: https://github.com/ImmPortDB/immport-galaxy-tools/tree/master/flowtools/flowai
type: unrestricted
